cirrus_container_task:
  auto_cancellation: true
  container:
    image: gcc:latest
  spec_script: ./.ci/spec.sh

cirrus_freebsd_task:
  auto_cancellation: true
  freebsd_instance:
    image: freebsd-11-2-release-amd64
  spec_script: ./.ci/spec.sh

cirrus_osx_task:
  auto_cancellation: true
  osx_instance:
    image: mojave-xcode
  spec_script: ./.ci/spec.sh
