env:
  INTEGROMAT_WEBHOOK_URL: ENCRYPTED[9c27f429840137201c54a77bb56ad8698d0ae2ba6f5a2ceaabc02671e198707d1f6ba516199ee546df281d8a14b2c9cb]

cirrus_container_task:
  auto_cancellation: true
  container:
    image: gcc:latest
  submodule_script: &su git submodule update --init --recursive
  spec_script: bash ./.ci/spec.sh

cirrus_freebsd_task:
  auto_cancellation: true
  freebsd_instance:
    image_family: freebsd-12-1-snap
  install_script: pkg install git
  submodule_script: *su
  spec_script: ./.ci/spec.sh

cirrus_osx_task:
  auto_cancellation: true
  osx_instance:
    image: catalina-xcode
  submodule_script: *su
  spec_script: ./.ci/spec.sh

cirrus_windows_task:
  auto_cancellation: true
  windows_container:
    image: cirrusci/windowsservercore:2019
    os_version: 2019
  submodule_script: *su
  spec_script: .ci/spec.bat
