env:
  INTEGROMAT_WEBHOOK_URL: ENCRYPTED[9c27f429840137201c54a77bb56ad8698d0ae2ba6f5a2ceaabc02671e198707d1f6ba516199ee546df281d8a14b2c9cb]

cirrus_container_task:
  auto_cancellation: true
  container:
    image: gcc:latest
  spec_script: bash ./.ci/spec.sh

cirrus_freebsd_task:
  auto_cancellation: true
  freebsd_instance:
    image: freebsd-11-2-release-amd64
  spec_script: ./.ci/spec.sh

cirrus_osx_task:
  auto_cancellation: true
  osx_instance:
    image: mojave-xcode
  spec_script: ./.ci/spec.sh

cirrus_windows_task:
  auto_cancellation: true
  windows_container:
    image: cirrusci/windowsservercore:2019
    os_version: 2019
  spec_script: C:/tools/msys64/usr/bin/bash -c .ci/spec.sh
  # spec_script: "C:\Program Files\Git\bin\Git\bin\bash\" -c \".ci\spec.sh\""
  # env:
  #   CIRRUS_SHELL: powershell
  # spec_script: |
  #   & 'C:\tools\msys64\usr\bin\bash' -c ".ci\spec.sh"
