kind: pipeline
type: docker
name: spec container

steps:
- name: spec
  image: golang
  environment:
    INTEGROMAT_WEBHOOK_URL:
      from_secret: INTEGROMAT_WEBHOOK_URL
  commands:
    - "./.ci/spec.sh"

# ---
# kind: pipeline
# type: exec
# name: spec mac

# platform:
#   os: darwin
#   arch: amd64

# steps:
# - name: spec
#   commands:
#     - "./.ci/spec.sh"

# ---
# kind: pipeline
# type: exec
# name: spec linux

# platform:
#   os: linux
#   arch: amd64

# steps:
# - name: spec
#   commands:
#     - "./.ci/spec.sh"

