version: v2

tasks:
  spec:
    containers:
      - image: iutest/razorops_test
    steps:
      - checkout
      - commands:
        - git submodule init
        - git submodule update
        - ./.ci/spec.sh
