dist: focal
language: cpp
script:
  - "./.ci/spec.sh"
env:
  global:
  - secure: zf/WVdE6j8uEp6cKEkDp6UjiiDjDoD/w0XvnJzKFz38UEWAR7FoaSUn+7kaPJmBU43c9IVQlE4yGmh8aPVNaxL7ljH8dBnfoKFjejjLqpfaPm1DgLn9EPZm95PwKAymhd7Z767rd9BjtqK16PqIfE+xSDjue24ImK8JnmXMETorvtvfx1aQ9QaKIe4KZ7wbJAS9CEPlU5++PIpB1TQg+MJRQBigvo2jjgO7R6OOl5+9hkeN6lLWB+hfPt7bzexhi9JsXgEP+yGwswnnqDLDrPnW+HIYoGtRzteNVpb70BMeAJ5JOJTREMYC3epFsVHvYLpKqcQVH5bGG14cQEoegb0ILlLqWHU14qMpBsRfXFynXVqDQYDRwZ7loL3yJ1FIq+zES34+KeDdzuY5D6zSXanxdbZBU/8XW0G7eY5yR1bPgxsEJjCef580EBK4wYUaFS37uC1WUqamC+P1rvNYFPXAPOzwmFy5kFU5c2iPd2NFCpzPrpBUWpOkZK7S6pXEYgUZ33qp8SDGfipsNtK6aPET1FXGrbLmzf9z/oyXW9Vafv9ktVk7Cc6s16z3+dZMLZwlYEE+yFpR3ACt2EkjIc8L0LKd8wwmPoFHWmbC9HWmKWsOfmACj4HvC6eJ7+ub0OJf0u7XwLN6sUwCRiukpCqPlZhwPGT9ibPWsaGLebkg=
matrix:
  include:
  - env: UPDATE_SUBMODULE=true
  - os: osx
    before_script:
    - echo osx
    script:
    - "./.ci/spec.sh"
  - os: windows
    before_script:
    - echo windows
    script:
    - "./.ci/spec.sh"
  - os: linux
    arch: amd64
    before_script:
    - echo linux
    script:
    - "./.ci/spec.sh"
  - os: linux
    arch: ppc64le
    before_script:
    - echo linux
    script:
    - "./.ci/spec.sh"
  - os: linux
    arch: s390x
    before_script:
    - echo linux
    script:
    - "./.ci/spec.sh"
  - os: linux
    arch: arm64
    before_script:
    - echo linux
    script:
    - "./.ci/spec.sh"
  - os: linux
    arch: arm64-graviton2
    before_script:
    - echo linux
    script:
    - "./.ci/spec.sh"
