version: 1.0.{build}
image:
  - macOS
  - Ubuntu
  - Visual Studio 2019

clone_depth: 1

build_script:
  sh: |
    ./.ci/spec.sh

for:
-
  matrix:
    only:
      - image: Visual Studio 2019
  build_script:
    sh: |
      bash ./.ci/spec.sh
