version: 1.0.{build}
image:
  - macOS
  - Ubuntu
  - Visual Studio 2019

# https://help.appveyor.com/discussions/problems/1272-fatal-reference-is-not-a-tree-sha-on-git-checkout
# clone_depth: 1

before_build:
  sh: |
    git submodule update --init --recursive

build_script:
  sh: |
    ./.ci/spec.sh

for:
-
  matrix:
    only:
      - image: Visual Studio 2019
  before_build:
    cmd: |
      git submodule update --init --recursive
  build_script:
    cmd: |
      bash ./.ci/spec.sh
