trigger:
- master

strategy:
  matrix:
    linux:
      imageName: 'ubuntu-latest'
    mac:
      imageName: 'macos-latest'
    windows:
      imageName: 'windows-latest'

pool:
  vmImage: $(imageName)

steps:
- bash: ./.ci/spec.sh
  env:
    INTEGROMAT_WEBHOOK_URL: $(INTEGROMAT_WEBHOOK_URL)
  displayName: 'spec'
