version: '1.0'
stages:
  - checkout
  - spec

steps:
  main_clone:
    title: Cloning main repository...
    type: git-clone
    stage: checkout
    repo: '${{CF_REPO_OWNER}}/${{CF_REPO_NAME}}'
    revision: '${{CF_REVISION}}'
  SpecTests:
    title: Spec
    stage: spec
    image: gcc:9
    commands:
      - ./.ci/spec.sh
