resources:
  - name: ci_specs_gitRepo
    type: GitRepo
    configuration:
      gitProvider: GitHub
      path: srz-zumix/ci-specs
      branches:
        include: master|^feature/.*|^jfrog/.*
pipelines:
  - name: ci_specs_centos
    configuration:
      nodePool: centos-latest
    steps:
      - name: spec
        type: Bash
        configuration: &config
          inputResources:
            - name: ci_specs_gitRepo
          integrations:
            - name: ci_specs_envs
          environmentVariables:
            readOnly:
              INTEGROMAT_WEBHOOK_URL: ${int_ci_specs_envs_INTEGROMAT_WEBHOOK_URL}
        execution: &exec
          onStart:
            - update_commit_status ci_specs_gitRepo # Status: "processing"
          onExecute:
            - update_commit_status ci_specs_gitRepo # Status: "processing"
            - pushd ${res_ci_specs_gitRepo_resourcePath}
            - git submodule update --init --recursive
            - .ci/spec.sh
            - popd
          onFailure:
            - update_commit_status ci_specs_gitRepo # Status: "failure"
          onSuccess:
            - update_commit_status ci_specs_gitRepo # Status: "success"
  - name: ci_specs_ubuntu
    configuration:
      nodePool: ubuntu-latest
    steps:
      - name: spec
        type: Bash
        configuration: *config
        execution: *exec
  - name: ci_specs_windows
    configuration:
      nodePool: windows-latest
    steps:
      - name: spec
        type: PowerShell
        configuration: *config
        execution: *exec
