resources:
  - name: gitRepo
    type: GitRepo
    configuration:
      gitProvider: GitHub
      path: srz-zumix/ci-specs
      branches:
        include:
          - master
          - ^feature/.*
pipelines:
  - name: centos
    configuration:
      nodePool: centos-latest
    steps:
      - name: spec
        type: Bash
        configuration:
          inputResources:
            - name: gitRepo
        execution:
          onExecute:
            - ${res_gitRepo_resourcePath}/.ci/spec.sh
