version: 2.1

orbs:
  win: circleci/windows@2.2.0

jobs:
  spec-win:
    executor: win/default
    steps:
      - checkout
      - &su
        run: git submodule update --init --recursive
      - run: bash ./.ci/spec.sh
  spec-linux:
    machine: true
    steps:
      - checkout
      - *su
      - run: ./.ci/spec.sh
  spec-mac:
    macos:
      xcode: 11.3.0
    steps:
      - checkout
      - *su
      - run: ./.ci/spec.sh
  spec:
    docker:
      - image: circleci/buildpack-deps:cosmic-browsers
    steps:
      - checkout
      - *su
      - run: ./.ci/spec.sh
  su:
    machine: true
    steps:
      - checkout
      - *su
      - run: ./.ci/update_submodule.sh

workflows:
  version: 2
  default-test:
    jobs:
      - spec-win
      - spec-linux
      # - spec-mac
      - spec
      - su
  maintenance:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - su
