on:
  push:
  pull_request:
    types:
      - assigned
      - unassigned
      - labeled
      - unlabeled
      - opened
      - edited
      - closed
      - reopened
      - synchronize
      - converted_to_draft
      - ready_for_review
      - locked
      - unlocked
      - review_requested
      - review_request_removed
      - auto_merge_enabled
      - auto_merge_disabled
  issue_comment:
  page_build:
  release:

name: Event Info
jobs:
  context:
    runs-on: ubuntu-18.04
    name: Show Context
    services:
      jenkins:
        image: jenkins/jenkins:latest
        credentials:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
        env:
          JAVA_OPTS: -Djenkins.install.runSetupWizard=false -Dcasc.jenkins.config=/casc_configs
        ports:
          - 8080:8080
          - 50000:50000
      agent1:
        image: ubuntu:latest
    steps:
    - name: $github
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: |
        echo "$GITHUB_CONTEXT"
    - name: $job
      env:
        JOB_CONTEXT: ${{ toJson(job) }}
      run: |
        echo "$JOB_CONTEXT"
    - name: ENV
      run: |
        env
    - uses: actions/checkout@v3
    - name: Composite Action Event
      uses: ./.github/actions/composite/events
