on:
  push:
  pull_request:
    types:
      - assigned
      - unassigned
      - labeled
      - unlabeled
      - opened
      - edited
      - closed
      - reopened
      - synchronize
      - converted_to_draft
      - ready_for_review
      - locked
      - unlocked
      - review_requested
      - review_request_removed
      - auto_merge_enabled
      - auto_merge_disabled
  issue_comment:
  page_build:
  release:

name: Event Info
jobs:
  context:
    runs-on: ubuntu-18.04
    name: Show Context
    steps:
    - name: $github
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: |
        echo "$GITHUB_CONTEXT"
    - name: ENV
      run: |
        env
    - name: Composite Action Event
      uses: ./.github/actions/composite/events
