on: [push, pull_request]

name: GitHub Actions
jobs:
  spec:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - uses: actions/checkout@master
      - run: sh ./.ci/spec.sh
